### ISSUE TITLE
hiding kind/image code for BufferedImage in configuration doesn't work

### ISSUE THREAD

**Issue by genmeblog** [scicloj/clay#105]
Configuring:

`:kindly/options {:kinds-that-hide-code #{:kind/image}}`

seems not working for BufferedImage, for example the following with above setup is still displayed (along with the image)

```clojure
(->  "https://upload.wikimedia.org/wikipedia/commons/2/2c/Clay-ss-2005.jpg"
     (java.net.URL.)
     (javax.imageio.ImageIO/read))
```

**Comment by genmeblog** [comment]
btw, what `kind/image` function supposes to do?

**Comment by daslu** [comment]
Zulip discussion: https://clojurians.zulipchat.com/#narrow/stream/422115-clay-dev/topic/images/near/444295831

**Comment by daslu** [comment]
Thanks, this is a bug: `:kind-that-hide-code` does not work for automatically inferred kinds like images, only for values explicitly annotated with kinds.

`kind/image` annotates a value with the kind metadata. If the value is a `BufferedImage` object, it wraps it with a vector first so that it will be possible to attach Clojure metadata. Due to an additional bug, that vector is not rendered correctly and raises an exception.
