### ISSUE TITLE
Feature request: option to set a fixed port

### ISSUE THREAD

**Issue by olavfosse** [scicloj/clay#107]
Use case: I run Clay on a server and I would like to view the visualisations locally. If I have a fixed port, I can just SSH port forward that and I'm good.

I implemented it in a backwards compatible way for my use case, but I think it would be nice to upstream.

Thoughts?

If the API looks ok, I'd love to send over a PR :D

<img width="821" alt="image" src="https://github.com/scicloj/clay/assets/24797093/8b0dad26-b217-42c7-990a-f38d34d26ed6">

**Comment by olavfosse** [comment]
I would like a way to automatically SSH port forward via the clay.el interface. CIDER handles that automatically. Not sure how to implement that tho :^)

**Comment by daslu** [comment]
Hi @olavfosse, thanks for this proposal, sounds important.

Regarding the API, we try to have user choices available through the Clay configuration so that users can control them on different levels (project / namespace / a single function call).
https://scicloj.github.io/clay/#configuration

Would you like to send me a private message on one of the other platforms (Zulip / Slack), so that we can possibly set a call?
I wish to hear your feedback regarding a few of the other UI aspects you've mentioned.

**Comment by daslu** [comment]
Hi @olavfosse, thanks for the call.

On the call, we decided that a PR like you proposed would be welcome.
Later, I can integrate this into the config system.
